import type { MethodologyContent } from "../../types";

export const UNEMPLOYMENT_METHODOLOGY_CONTENT: MethodologyContent = {
  id: "unemployment", slug: "unemployment", title: "Unemployment and the labour force",
  summary: "Annual Geostat survey estimates of unemployment, employment and participation, with the published sex, settlement, age, regional and education comparisons.",
  reviewedAt: "2026-10-06", archiveManifestId: "unemployment", coverageSource: { kind: "archive" },
  canonicalDocuments: ["docs/data-methodology/unemployment-annual.md"],
  disclosure: "These are official Labour Force Survey estimates, not a census. Fiscal.ge displays the published annual observations without filling gaps or calculating new education counts.",
  keyFacts: [{ label: "Coverage", valueKind: "coverage" }, { label: "Frequency", valueKind: "frequency", value: "Annual" }, { label: "Status", valueKind: "basis", value: "Actual survey estimates" }, { label: "Units", valueKind: "unit", value: "% / thousand persons" }],
  sections: [
    { id: "scope", kind: "scope", title: "What the figures mean", paragraphs: ["Unemployed people have no employment, actively sought work during the preceding four weeks and can start within two weeks. Employed people worked for pay or profit for at least one hour in the reference week, or were temporarily absent from a job.", "Employed people include hired employees, the self-employed and a small unclassified worker group. The two displayed subcategories therefore do not add up to the complete employed total. The labour force comprises employed and unemployed people. The survey population aged 15+ also includes people outside the labour force. Being outside the labour force is different from being unemployed."] },
    { id: "rates", kind: "sources", title: "Which denominator is used?", paragraphs: ["Unemployment rate = unemployed / matching labour force × 100. Employment rate = employed / matching survey population aged 15+ × 100. Participation rate = labour force / matching survey population aged 15+ × 100. Group rates use that group's denominator; they are never averaged into a national rate.", "Long-term unemployment means 12 months or more. Its rate divides long-term unemployed people by the matching labour force; its share divides them by all matching unemployed people. These percentages answer different questions.", "Education publishes three rates for four levels, separately for total, women and men, from 2020. The reference is the separately published national or matching sex rate. No education counts or rates for the unpublished No education category are inferred."] },
    { id: "classification", kind: "classification", title: "Compare like with like", paragraphs: ["Comparable core data begin in 2010. Pre-2010 observations use a different definition and are retained only inside the source archive. Ten-year age bands are published through 2019; five-year bands begin in 2020. The two are separate series.", "Imereti combined with Racha-Lechkhumi and Kvemo Svaneti ends in 2018; separate figures begin in 2019. Samtskhe-Javakheti combined with Guria and Mtskheta-Mtianeti ends in 2016; separate figures begin in 2017. Combined historical values are never assigned to one member. Education and long-term data begin in 2020. Regional hired and self-employed counts are also published only for 2020–2025; earlier years remain unavailable.", "The Integrated Household Survey supplied data through 2016; the separate Labour Force Survey began in 2017. The metadata explains sampling-frame and census-based revisions."] },
    { id: "validation", kind: "validation", title: "How the figures are checked", paragraphs: ["All 3,370 serving observations retain their exact source decimal values and worksheet references. Checks cover the nine original fingerprints, complete group/year inventories, count sums, the labour-force and population identities and each rate's matching denominator. Values display to one decimal; the retained calculation precision does not imply extra sampling accuracy.", "The national population chart stacks the three mutually exclusive counts: employed, unemployed and outside the labour force. It uses the same survey population, not a demographic population estimate. Missing observations are shown as gaps or dashes, never zero."] },
    { id: "limitations", kind: "limitations", title: "Survey limitations", paragraphs: ["The survey covers private households and excludes occupied territories and institutional households. Differences and rankings are estimates; this explorer does not establish statistical significance. The metadata's 2025 national unemployment-rate confidence interval is 13.0–14.8%, with a standard error of 0.5 percentage points; it is not an interval for every displayed group.", "Quarterly data, forecasts, municipal unemployment, NEET and new derived comparisons are outside this annual explorer. Excel downloads contain the selected indicators, selected groups and years, with source links."] },
    { id: "archive", kind: "archive", title: "Original sources", paragraphs: ["The archive preserves seven Geostat workbooks, the source-page capture and Labour Force Survey metadata, retrieved on 3 October 2026. Some originals also contain older or quarterly observations; those do not extend this explorer's coverage."] },
  ], decisions: [], technicalAppendix: [], showTechnicalAppendix: false,
};
