import { expect, test } from "vitest";
import { toClientForeignInvestmentData } from "../../lib/data/externalFlows/importForeignInvestment";
import { toClientMoneyTransfersData } from "../../lib/data/externalFlows/importMoneyTransfers";
import { buildExternalHubCards } from "../../lib/explorer/externalHubCards";
import type { ClientCurrentAccountFact } from "../../lib/data/externalFlows/importCurrentAccount";
import { foreignInvestmentEntities, foreignInvestmentFacts, moneyTransferEntities, moneyTransferFacts } from "../data/externalFlows/fixtures";
test("the hub has working Money from abroad, Foreign investment and Current account cards", () => {
  const money = toClientMoneyTransfersData({ entities: moneyTransferEntities(), facts: moneyTransferFacts() });
  const investment = toClientForeignInvestmentData({ entities: foreignInvestmentEntities(), facts: foreignInvestmentFacts() });
  const messages = { "external.money.title": "Money from abroad", "external.money.summary": "Transfers", "external.annual": "annual", "external.investment.title": "Foreign investment", "external.investment.summary": "FDI", "external.account.title": "Current account", "external.account.summary": "BoP" };
  const account: ClientCurrentAccountFact[] = [{ seriesId: "ca.balance", flow: "net", year: 2000, valueUsd: -176 }, { seriesId: "ca.balance", flow: "net", year: 2001, valueUsd: -197 }, { seriesId: "ca.balance", flow: "credit", year: 2001, valueUsd: 900 }, { seriesId: "ca.goods", flow: "net", year: 2001, valueUsd: -500 }];
  const cards = buildExternalHubCards(money, investment, account, { locale: "en", englishLabels: {}, messages });
  expect(cards.map(card => [card.href, card.comingSoon])).toEqual([["/explorer/external/money-from-abroad", false], ["/explorer/external/foreign-investment", false], ["/explorer/external/current-account", false]]);
  expect(cards[0].series).toEqual([...Array(12).fill(null), 1000]);
  expect(cards[0].footer).toBe("2007–2019 · annual");
  expect(cards[1].series).toEqual([1000]);
  expect(cards[1].footer).toBe("2015–2015 · annual");
  expect(cards[2].series).toEqual([-176, -197]);
  expect(cards[2].footer).toBe("2000–2001 · annual");
  expect(cards.slice(1).map(card => card.title)).toEqual(["Foreign investment", "Current account"]);
});
