import { renderToStaticMarkup } from "react-dom/server";
import { beforeAll, expect, test } from "vitest";
import { UnemploymentExplorer } from "../../components/unemployment/unemployment-explorer";
import { loadServedUnemploymentData, UNEMPLOYMENT_GROUPS } from "../../lib/data/unemployment/importUnemployment";
import { I18nProvider } from "../../lib/i18n/provider";
import { getMessages } from "../../lib/i18n/messages.server";
import type { ClientUnemploymentObservation } from "../../lib/data/unemployment/types";
let facts: ClientUnemploymentObservation[];
beforeAll(async () => { facts = (await loadServedUnemploymentData()).facts; });
test.each(["ka", "en"] as const)("renders the existing workspace, two chart types and national-only default in %s", async locale => {
  const messages = await getMessages(locale, ["unemployment", "common", "controls", "main", "format", "workbook"]);
  const markup = renderToStaticMarkup(<I18nProvider locale={locale} messages={messages}><UnemploymentExplorer section="overview" facts={facts} registry={UNEMPLOYMENT_GROUPS} sources={[]} lastReviewedAt="2026-10-03" siteOrigin="https://fiscal.ge" /></I18nProvider>);
  expect(markup).toContain('data-testid="explorer-workspace"');
  expect(markup).toContain('data-testid="chart-mode-table"');
  expect(markup).not.toContain('data-testid="unemployment-indicator"');
  expect(markup).toContain('data-series-id="georgia:unemployment_rate"');
  expect(markup).toContain('data-series-id="georgia:employed"');
  expect(markup).not.toContain('data-series-id="georgia"');
  expect(markup).toContain('data-testid="unemployment-national-tabs"');
  expect(markup).not.toContain('data-testid="unemployment-headline"');
  const heading = markup.slice(0, markup.indexOf('data-testid="unemployment-national-tabs"'));
  expect(heading).toContain(messages["unemployment.page.overview.title"]);
  expect(heading).toContain(messages["unemployment.page.overview.summary"]);
  expect(heading).not.toContain(messages["unemployment.surveyEstimate"]);
  // Before the browser measures, each chart renders its desktop and its phone drawing (D1).
  expect(markup.match(/<svg[^>]*data-geometry="desktop"[^>]*role="img"/g)).toHaveLength(2);
  expect(markup.match(/<svg[^>]*data-geometry="mobile"[^>]*role="img"/g)).toHaveLength(2);
  expect(markup.match(/role="img"/g)).toHaveLength(4);
  expect(markup.match(/<path[^>]+stroke="#1E1B16"/g)).toHaveLength(2);
  expect(markup).toContain("13.9%");
  expect(markup).toContain("2010–2025");
  expect(markup).toContain('data-testid="unemployment-excel-download"');
  expect(markup).not.toMatch(/Amount \(GEL\)|თანხა \(₾\)/);
  expect(markup).toContain(locale === "en" ? "Survey estimates" : "კვლევის შეფასებები");
});
