import { renderToStaticMarkup } from "react-dom/server";
import { beforeAll, expect, test } from "vitest";
import { UnemploymentExplorer } from "../../components/unemployment/unemployment-explorer";
import { loadServedUnemploymentData, UNEMPLOYMENT_GROUPS } from "../../lib/data/unemployment/importUnemployment";
import { I18nProvider } from "../../lib/i18n/provider";
import { getMessages } from "../../lib/i18n/messages.server";
import type { ClientUnemploymentObservation } from "../../lib/data/unemployment/types";
let facts: ClientUnemploymentObservation[];
beforeAll(async () => { facts = (await loadServedUnemploymentData()).facts; });
test.each(["ka", "en"] as const)("renders the existing workspace, two chart types and national-only default in %s", async locale => {
  const messages = await getMessages(locale, ["unemployment", "common", "controls", "main", "format", "workbook"]);
  const markup = renderToStaticMarkup(<I18nProvider locale={locale} messages={messages}><UnemploymentExplorer facts={facts} registry={UNEMPLOYMENT_GROUPS} sources={[]} lastReviewedAt="2026-10-03" siteOrigin="https://fiscal.ge" /></I18nProvider>);
  expect(markup).toContain('data-testid="explorer-workspace"');
  expect(markup).toContain('data-testid="chart-mode-table"');
  expect(markup).toContain('data-testid="unemployment-indicator"');
  expect(markup).toContain('data-testid="unemployment-breakdown"');
  expect(markup.match(/role="img"/g)).toHaveLength(2);
  expect(markup.match(/<path[^>]+stroke="#1E1B16"/g)).toHaveLength(1);
  expect(markup).toContain("13.9%");
  expect(markup).toContain("2010–2025");
  expect(markup).toContain('data-testid="unemployment-excel-download"');
  expect(markup).not.toMatch(/Amount \(GEL\)|თანხა \(₾\)/);
  expect(markup).toContain(locale === "en" ? "Survey estimates" : "კვლევის შეფასებები");
});
